USE SUCOS;

ALTER TABLE tbProduto ADD PRIMARY KEY (PRODUTO);

/* ESSA INSERÇÃO GERARÁ ERRO, POIS JÁ EXISTE UM PRODUTO COM O 
    MESMO CÓDIGO CADASTRADO */
INSERT INTO tbProduto 
(
PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA
) VALUES (
'1004327', 'Videira do Campo - 1,5 Litros - Melancia', 'PET',
'1,5 Litros', 'Melancia', 19.51
);