USE SUCOS;

ALTER TABLE tbCliente ADD PRIMARY KEY (CPF);

ALTER TABLE tbCliente ADD COLUMN (DATA_NASCIMENTO DATE);

INSERT INTO tbCliente (
CPF, NOME, ENDERECO1, ENDERECO2, BAIRRO, CIDADE, ESTADO, CEP,
IDADE, SEXO, LIMITE_CREDITO, VOLUME_COMPRA, PRIMEIRA_COMPRA, 
DATA_NASCIMENTO) VALUES (
'00388993405', 'João da Silva', 'Rua Projetada A, número 10', 
'', 'Vila Roman', 'Caratinga', 'Minas Gerais', '22222222', 30, 
'M', 10000.00, 2000.00, 0, '1989-10-05');

SELECT * FROM tbCliente;

ALTER TABLE tabela_de_vendedores ADD PRIMARY KEY (MATRICULA);
ALTER TABLE tabela_de_vendedores ADD COLUMN (DATA_ADMISSAO DATE);
ALTER TABLE tabela_de_vendedores ADD COLUMN (DE_FERIAS BIT(1));

UPDATE tabela_de_vendedores SET DATA_ADMISSAO = '2014-08-15'
WHERE MATRICULA = '00235';

UPDATE tabela_de_vendedores SET DE_FERIAS = 0 
WHERE MATRICULA = '00235';

UPDATE tabela_de_vendedores SET DATA_ADMISSAO = '2013-09-17'
WHERE MATRICULA = '00236';

UPDATE tabela_de_vendedores SET DE_FERIAS = 1
WHERE MATRICULA = '00236';

INSERT INTO tabela_de_vendedores (
MATRICULA, NOME, PERCENTUAL_COMISSAO, DATA_ADMISSAO, DE_FERIAS)
VALUES ('00237', 'Roberta Martins', 0.11, '2017-03-18', 1);

INSERT INTO tabela_de_vendedores (MATRICULA, NOME, 
PERCENTUAL_COMISSAO, DATA_ADMISSAO, DE_FERIAS) VALUES (
'00238', 'Péricles Alves', 0.11, '2016-08-21', 0);

SELECT * FROM tabela_de_vendedores;