USE sucos;

SELECT * FROM tbCliente;

SELECT CPF, NOME, ENDERECO1, ENDERECO2, BAIRRO, CIDADE,
ESTADO, CEP, IDADE, SEXO, LIMITE_CREDITO, VOLUME_COMPRA,
PRIMEIRA_COMPRA, DATA_NASCIMENTO FROM tbcliente;

SELECT CPF, NOME FROM tbcliente;

SELECT CPF, NOME FROM tbcliente LIMIT 5;

SELECT CPF AS CPF_CLIENTE, NOME AS NOME_CLIENTE FROM tbcliente;

SELECT NOME, CPF, IDADE, SEXO, DATA_NASCIMENTO FROM tbcliente;

SELECT NOME, MATRICULA FROM tabela_de_vendedores;